Repository Autodesk/arnold-usd, pull requests merged in 2020-08, with the labels that each got.

#489 Implementing alternative HdRenderDelegate::CreateRenderDelegate function override
  render_delegate/renderer_plugin.cpp
  render_delegate/renderer_plugin.h
Labels: bug, houdini, render delegate

#491 Allow overwriting the build directory
  SConstruct
Labels: build, enhancement

#493 Documenting the use of the CMake build system
  docs/building.md
Labels: build, docs

#499 Fixing building for Katana on Windows
  SConstruct
  cmake/modules/FindArnold.cmake
  cmake/utils/options.cmake
  procedural/SConscript
  schemas/SConscript
  tools/utils/dependencies.py
  translator/reader/utils.cpp
Labels: bug, build, katana

#497 Add support for custom procedurals
  testsuite/test_0137/README
  testsuite/test_0137/data/test.ass
  testsuite/test_0137/ref/reference.log
  testsuite/test_0137/ref/reference.tif
  translator/reader/prim_reader.cpp
  translator/reader/read_geometry.cpp
  translator/reader/read_geometry.h
  translator/reader/read_options.cpp
  translator/reader/read_options.h
  translator/reader/read_shader.cpp
  translator/reader/registry.cpp
  translator/writer/registry.cpp
  translator/writer/write_geometry.cpp
  translator/writer/write_geometry.h
Labels: enhancement, procedural, schema, writer

#495 Updating readme and release notes for the 6.0.4.0 release
  CHANGELOG.md
  README.md
Labels: docs

#502 Using modff instead of modf in basis_curves
  render_delegate/basis_curves.cpp
Labels: bug, build, katana

#503 Improve the schemas builds
  schemas/createSchemaFile.py
Labels: enhancement, schema

#514 Viewport representation in points mode now reads the matrix
  translator/reader/read_geometry.cpp
Labels: bug, procedural
