Repository Autodesk/arnold-usd, pull requests merged in 2020-06, with the labels that each got.

#457 Updating release notes and readme for 6.0.3.1.
  CHANGELOG.md
  README.md
Labels: docs

#454 Support UsdRender schemas in the reader
  testsuite/test_0133/README
  testsuite/test_0133/data/test.usda
  testsuite/test_0133/ref/reference.log
  testsuite/test_0133/ref/reference.tif
  translator/CMakeLists.txt
  translator/reader/read_options.cpp
  translator/reader/read_options.h
  translator/reader/registry.cpp
Labels: enhancement, scene format

#464 Extending support for primvar types read in the procedural
  testsuite/test_0135/README
  testsuite/test_0135/data/test.usda
  testsuite/test_0135/ref/reference.log
  testsuite/test_0135/ref/reference.tif
  translator/reader/prim_reader.cpp
Labels: bug, procedural, user

#461 Using single element arrays to set parameters
  render_delegate/utils.cpp
  render_delegate/utils.h
  testsuite/CMakeLists.txt
  testsuite/groups
  testsuite/test_0134/README
  testsuite/test_0134/data/test.cpp
Labels: enhancement, houdini, render delegate, user

#459 Adding documentation for building for USD 20.05 and Houdini 18.0 on Linux
  cmake/modules/FindUSD.cmake
  docs/building.md
  procedural/SConscript
  tools/utils/dependencies.py
  translator/CMakeLists.txt
  translator/SConscript
Labels: build, docs, user

#470 Removing insensitive terminology
  schemas/createSchemaFile.py
  testsuite/SConscript
  testsuite/test_0015/ref/reference.log
  tools/utils/contrib/bottle/__init__.py
Labels: enhancement
