Repository Autodesk/arnold-usd, pull requests merged in 2020-01, with the labels that each got.

#136 Checking for root layer validity when loading the file.
  translator/reader/reader.cpp
Labels: bug, procedural

#118 Removing BUILD_HOUDINI_TOOLS and all associated documentation from the build and codebase
  SConstruct
  docs/building.md
  render_delegate/SConscript
  render_delegate/volume.cpp
  render_delegate/volume.h
Labels: houdini, render delegate

#139 Fixing a crash in the procedural when matrix arrays are empty
  translator/reader/prim_reader.cpp
Labels: bug, crash, procedural

#141 Missing bits from pull request 133
  render_delegate/constant_strings.h
Labels: bug, build, render delegate

#146 Writer clears the list of exported attributes for every node
  translator/writer/prim_writer.cpp
  translator/writer/prim_writer.h
  translator/writer/write_arnold_type.cpp
  translator/writer/write_arnold_type.h
  translator/writer/write_geometry.cpp
  translator/writer/write_light.cpp
  translator/writer/write_shader.cpp
  translator/writer/write_shader.h
  translator/writer/writer.cpp
Labels: bug, procedural

#156 Reversing render context priority in the procedural
  testsuite/test_0014/data/scene.usda
  translator/reader/utils.cpp
Labels: enhancement, procedural

#159 Supporting SdfAssetPath on shaders
  testsuite/test_0015/data/red.png
  testsuite/test_0015/data/scene.usda
  testsuite/test_0015/ref/reference.log
  testsuite/test_0015/ref/reference.tif
  translator/reader/prim_reader.cpp
Labels: bug, procedural

#161 Fixing build issue with the latest USD releases
  render_delegate/material.cpp
Labels: bug, build, render delegate

#167 Append _GLIBCXX_USE_CXX11_ABI to CPPDEFINES instead of CCFLAGS
  SConstruct
Labels: bug, build

#175 Automatically detect if ai_scene_format.h is available.
  SConstruct
  procedural/SConscript
  procedural/main.cpp
  tools/utils/build_tools.py
Labels: build, procedural

#177 Set _triggers_reload metadata on procedural attributes
  procedural/main.cpp
Labels: bug, procedural

#184 Updating scene file for test 14
  testsuite/test_0014/data/scene.usda
Labels: bug, procedural

#186 Reverting change to support HdChangeTracker::DirtyPoints.
  render_delegate/mesh.cpp
Labels: bug, render delegate
