Repository Autodesk/arnold-usd, pull requests merged in 2021-12, with the labels that each got.

#943 Set product metadata. (#933)
  render_delegate/render_delegate.cpp
Labels: bug, render delegate

#948 Add support for primvars on instances #944
  testsuite/test_0186/README
  testsuite/test_0186/data/test.usda
  testsuite/test_0186/ref/reference.log
  testsuite/test_0186/ref/reference.tif
  testsuite/test_0187/README
  testsuite/test_0187/data/asset.usda
  testsuite/test_0187/data/scene.usda
  testsuite/test_0187/data/test.ass
  testsuite/test_0187/ref/reference.log
  testsuite/test_0187/ref/reference.tif
  translator/reader/prim_reader.cpp
  translator/reader/prim_reader.h
  translator/reader/read_geometry.cpp
  translator/reader/reader.cpp
  translator/reader/utils.cpp
  translator/reader/utils.h
Labels: enhancement, procedural

#952 Call AiResolveFilePath with procedural type
  procedural/main.cpp
Labels: bug, procedural

#958 Support USD 21.11
  schemas/SConscript
  schemas/createSchemaFile.py
  translator/reader/read_light.cpp
  translator/writer/write_light.cpp
Labels: bug

#961 Fix build of usd_imaging with USD 21.11 #957
  usd_imaging/usd_lux_light_filter_adapter.cpp
Labels: bug, build

#965 Fix inherited primvars on instanceable prims
  testsuite/test_0188/README
  testsuite/test_0188/data/cube.usd
  testsuite/test_0188/data/native_instance_cubes.usd
  testsuite/test_0188/data/scene.usda
  testsuite/test_0188/ref/reference.log
  testsuite/test_0188/ref/reference.tif
  translator/reader/reader.cpp
Labels: bug, procedural

#974 Merging sirpalee/dev to master branch
  .gitignore
  SConstruct
  cmake/modules/FindArnold.cmake
  cmake/modules/FindMaterialX.cmake
  cmake/modules/FindUSD.cmake
  cmake/utils/options.cmake
  cmd/CMakeLists.txt
  common/api.h
  common/constant_strings.h
  docs/CMakeLists.txt
  docs/building.md
  ndr/parser.cpp
  ndr/tokens.cpp
  ndr/tokens.h
  render_delegate/CMakeLists.txt
  render_delegate/SConscript
  render_delegate/basis_curves.cpp
  render_delegate/hdarnold.h
  render_delegate/light.cpp
  render_delegate/material.h
  render_delegate/material_tracker.cpp
  render_delegate/mesh.cpp
  render_delegate/native_rprim.cpp
  render_delegate/node_graph.cpp
  render_delegate/node_graph.h
  render_delegate/node_graph_tracker.cpp
  render_delegate/node_graph_tracker.h
  render_delegate/points.cpp
  render_delegate/render_delegate.cpp
  render_delegate/render_delegate.h
  render_delegate/rprim.h
  render_delegate/utils.cpp
  render_delegate/volume.cpp
  render_delegate/volume.h
  schemas/createSchemaFile.py
  tools/utils/dependencies.py
  translator/reader/read_light.cpp
  usd_imaging/CMakeLists.txt
  usd_imaging/SConscript
  usd_imaging/material_param_utils.cpp
  usd_imaging/material_param_utils.h
  usd_imaging/node_graph_adapter.cpp
  usd_imaging/node_graph_adapter.h
  usd_imaging/plugInfo.json.in
  usd_imaging/usd_lux_light_filter_adapter.cpp
Labels: enhancement, render delegate, schema, build, user, imaging

#979 Extend skinning interval to surrounding integer frames
  testsuite/test_0190/README
  testsuite/test_0190/data/scene.usda
  testsuite/test_0190/ref/reference.log
  testsuite/test_0190/ref/reference.tif
  translator/reader/reader.cpp
Labels: bug, procedural

#977 Support Curves st primvars in the procedural
  testsuite/test_0189/README
  testsuite/test_0189/data/scene.usda
  testsuite/test_0189/ref/reference.log
  testsuite/test_0189/ref/reference.tif
  translator/reader/prim_reader.cpp
  translator/reader/read_geometry.cpp
  translator/reader/utils.cpp
  translator/reader/utils.h
Labels: bug, procedural

#983 Fixing compilation issues when using Visual Studio 2019
  CMakeLists.txt
Labels: build, user

#985 Fix build issues in material_param_utils with USD 21.08
  usd_imaging/material_param_utils.cpp
Labels: bug, imaging

#988 Light and shadow links default ignoreRoots to false
  testsuite/test_0192/README
  testsuite/test_0192/data/scene.usda
  testsuite/test_0192/ref/reference.log
  testsuite/test_0192/ref/reference.tif
  translator/reader/read_light.cpp
  translator/reader/reader.cpp
Labels: bug, procedural

#986 Read usd builtin normals in meshes
  testsuite/test_0035/ref/reference.log
  testsuite/test_0035/ref/reference.tif
  testsuite/test_0131/ref/reference.log
  testsuite/test_0131/ref/reference.tif
  testsuite/test_0191/README
  testsuite/test_0191/data/scene.usda
  testsuite/test_0191/ref/reference.log
  testsuite/test_0191/ref/reference.tif
  translator/reader/read_geometry.cpp
Labels: procedural

#989 Adding support for atmosphere and background shaders
  common/constant_strings.h
  render_delegate/render_delegate.cpp
  render_delegate/render_delegate.h
  render_delegate/render_pass.cpp
Labels: enhancement, render delegate

#990 Read UsdLuxShadowAPI parameters #945
  common/constant_strings.h
  testsuite/test_0193/README
  testsuite/test_0193/data/scene.usda
  testsuite/test_0193/ref/reference.log
  testsuite/test_0193/ref/reference.tif
  translator/reader/read_light.cpp
Labels: bug, procedural

#992 Support connections to array elements in the delegate
  render_delegate/node_graph.cpp
  testsuite/test_0048/data/scene.usda
Labels: bug, render delegate
