Repository Autodesk/arnold-usd, pull requests merged in 2021-03, with the labels that each got.

#676 Read velocities from point based schemas
  testsuite/test_0157/README
  testsuite/test_0157/data/scene.usda
  testsuite/test_0157/data/test.ass
  testsuite/test_0157/ref/reference.log
  testsuite/test_0157/ref/reference.tif
  translator/reader/read_geometry.cpp
Labels: bug, procedural

#677 Adding support for the pause/resume API
  render_delegate/render_delegate.cpp
  render_delegate/render_delegate.h
  render_delegate/render_param.cpp
  render_delegate/render_param.h
  render_delegate/render_pass.cpp
Labels: enhancement, render delegate, user

#680 Add support for NodeGraph primitives in the procedural
  testsuite/test_0158/README
  testsuite/test_0158/data/scene.usda
  testsuite/test_0158/data/test.ass
  testsuite/test_0158/ref/reference.log
  testsuite/test_0158/ref/reference.tif
  translator/reader/prim_reader.cpp
  translator/reader/prim_reader.h
  translator/reader/read_light.cpp
  translator/reader/read_shader.cpp
  translator/reader/read_shader.h
  translator/reader/reader.cpp
  translator/reader/reader.h
  translator/reader/utils.cpp
Labels: enhancement, procedural

#681 Read render settings at the proper frame
  testsuite/test_0158/data/test.ass
  testsuite/test_0159/README
  testsuite/test_0159/data/test.usda
  testsuite/test_0159/ref/reference.log
  testsuite/test_0159/ref/reference.tif
  translator/reader/read_options.cpp
Labels: bug, procedural, scene format

#682 Prevent crashes in the writer by solving invalid naming conventions
  testsuite/test_0160/README
  testsuite/test_0160/data/test.ass
  testsuite/test_0160/ref/reference.log
  testsuite/test_0160/ref/reference.tif
  translator/writer/prim_writer.cpp
Labels: bug, writer

#684 Don't apply skinning if a cache ID is set
  translator/reader/reader.cpp
Labels: bug, procedural

#686 Support nested procedurals matrices for viewport display
  testsuite/test_0161/README
  testsuite/test_0161/data/cube.usda
  testsuite/test_0161/data/nested_proc.usda
  testsuite/test_0161/data/scene.ass
  testsuite/test_0161/data/test.cpp
  testsuite/test_0161/ref/reference.log
  testsuite/test_0161/ref/reference.tif
  testsuite/test_0162/README
  testsuite/test_0162/data/nested_proc.usda
  testsuite/test_0162/data/scene.ass
  testsuite/test_0162/data/sphere.usda
  testsuite/test_0162/data/test.cpp
  testsuite/test_0162/ref/reference.log
  testsuite/test_0162/ref/reference.tif
  translator/reader/read_geometry.cpp
  translator/reader/read_geometry.h
  translator/reader/registry.cpp
Labels: bug, procedural

#688 Prevent crashes with empty primvars arrays
  testsuite/test_0163/README
  testsuite/test_0163/data/scene.usda
  testsuite/test_0163/data/test.ass
  testsuite/test_0163/ref/reference.log
  testsuite/test_0163/ref/reference.tif
  translator/reader/utils.h
Labels: bug, crash, procedural

#696 Support mesh creases in the procedural
  testsuite/test_0169/README
  testsuite/test_0169/data/scene.usda
  testsuite/test_0169/data/test.ass
  testsuite/test_0169/ref/reference.log
  testsuite/test_0169/ref/reference.tif
  translator/reader/read_geometry.cpp
Labels: enhancement, procedural

#697 Support instanceable prims
  testsuite/test_0166/README
  testsuite/test_0166/data/asset.usda
  testsuite/test_0166/data/scene.usda
  testsuite/test_0166/data/test.ass
  testsuite/test_0166/ref/reference.log
  testsuite/test_0166/ref/reference.tif
  translator/reader/reader.cpp
  translator/reader/reader.h
Labels: enhancement, procedural

#698 Support purpose in the procedural
  procedural/main.cpp
  testsuite/test_0167/README
  testsuite/test_0167/data/cube_proxy.usda
  testsuite/test_0167/data/cube_render.usda
  testsuite/test_0167/data/scene.usda
  testsuite/test_0167/data/test.ass
  testsuite/test_0167/ref/reference.log
  testsuite/test_0167/ref/reference.tif
  testsuite/test_0168/README
  testsuite/test_0168/data/cube_proxy.usda
  testsuite/test_0168/data/cube_render.usda
  testsuite/test_0168/data/scene.ass
  testsuite/test_0168/data/scene.usda
  testsuite/test_0168/data/test.cpp
  testsuite/test_0168/ref/reference.log
  testsuite/test_0168/ref/reference.tif
  translator/reader/reader.cpp
  translator/reader/reader.h
Labels: enhancement, procedural

#699 Support UsdTransform2d shader in the procedural
  testsuite/test_0170/README
  testsuite/test_0170/data/test.usda
  testsuite/test_0170/data/texture.tx
  testsuite/test_0170/ref/reference.log
  testsuite/test_0170/ref/reference.tif
  translator/reader/read_shader.cpp
Labels: enhancement, procedural

#700 Adding a set of common strings to use between the different modules
  CMakeLists.txt
  SConstruct
  common/constant_strings.cpp
  common/constant_strings.h
  common/shape_utils.cpp
  common/shape_utils.h
  ndr/CMakeLists.txt
  ndr/SConscript
  render_delegate/CMakeLists.txt
  render_delegate/SConscript
  render_delegate/basis_curves.cpp
  render_delegate/camera.cpp
  render_delegate/light.cpp
  render_delegate/material.cpp
  render_delegate/mesh.cpp
  render_delegate/nodes/driver_aov.cpp
  render_delegate/nodes/driver_main.cpp
  render_delegate/nodes/nodes.cpp
  render_delegate/points.cpp
  render_delegate/render_delegate.cpp
  render_delegate/render_pass.cpp
  render_delegate/shape.cpp
  render_delegate/utils.cpp
  render_delegate/volume.cpp
  translator/CMakeLists.txt
  translator/SConscript
  translator/reader/prim_reader.cpp
  translator/reader/read_camera.cpp
  translator/reader/read_geometry.cpp
  translator/reader/read_light.cpp
  translator/reader/read_options.cpp
  translator/reader/read_shader.cpp
  translator/reader/reader.cpp
  translator/reader/utils.cpp
Labels: enhancement, procedural, render delegate

#702 Convert half and double tuples to arnold types
  testsuite/test_0172/README
  testsuite/test_0172/data/scene.usd
  testsuite/test_0172/data/test.ass
  testsuite/test_0172/ref/reference.log
  testsuite/test_0172/ref/reference.tif
  translator/reader/prim_reader.cpp
  translator/reader/utils.h
Labels: enhancement, procedural

#703 Adding half support for VtValueGetFloat.
  testsuite/test_0172/ref/reference.log
  testsuite/test_0172/ref/reference.tif
  translator/reader/utils.h
Labels: crash, procedural

#704 Fixing test 166
  testsuite/test_0166/data/test.ass
Labels: bug

#706 Simplifying schema build and installation
  CMakeLists.txt
  SConstruct
  cmake/utils/options.cmake
  schemas/CMakeLists.txt
  schemas/SConscript
  schemas/updatePlugInfo.py
Labels: build, enhancement, imaging

#708 Using USD_PATH instead of USD_LOCATION + bin in schemas/SConscript
  schemas/SConscript
Labels: bug, build

#709 Use a WorkDispatcher for parallel reading of the procedural
  procedural/SConscript
  procedural/main.cpp
  testsuite/test_0016/data/test.ass
  tools/utils/dependencies.py
  translator/CMakeLists.txt
  translator/SConscript
  translator/reader/prim_reader.cpp
  translator/reader/read_geometry.cpp
  translator/reader/read_light.cpp
  translator/reader/read_options.cpp
  translator/reader/reader.cpp
  translator/reader/reader.h
  translator/reader/utils.cpp
  translator/reader/utils.h
Labels: enhancement, procedural

#712 Setting render context hint
  common/constant_strings.h
  render_delegate/render_delegate.cpp
Labels: enhancement, render delegate

#716 Fixing initialization order issues related to constant_strings.h
  ndr/CMakeLists.txt
  ndr/SConscript
  render_delegate/CMakeLists.txt
  render_delegate/SConscript
  render_delegate/material.cpp
  tools/utils/dependencies.py
  translator/CMakeLists.txt
  translator/SConscript
  usd_imaging/CMakeLists.txt
  usd_imaging/SConscript
Labels: bug, build

#719 Don't render inactive renderVars
  testsuite/test_0173/README
  testsuite/test_0173/data/test.usda
  testsuite/test_0173/ref/reference.log
  testsuite/test_0173/ref/reference.tif
  translator/reader/read_options.cpp
Labels: scene format

#721 Add option to save all attributes to usd
  common/constant_strings.h
  procedural/main.cpp
  testsuite/test_0174/README
  testsuite/test_0174/data/test.cpp
  translator/writer/prim_writer.cpp
  translator/writer/writer.h
Labels: enhancement, user, writer

#723 Fixing build issues on macOS and targeting Houdini USD libraries
  schemas/SConscript
Labels: bug, build

#728 Supporting wrapS, wrapT, offset and bias parameters on UsdUvTexture
  common/constant_strings.h
  render_delegate/material.cpp
Labels: bug, render delegate, user

#729 Change render context hint from interactive to hydra. (#711)
  common/constant_strings.h
  render_delegate/render_delegate.cpp
Labels: enhancement, render delegate

#733 Support uvTexture wrap, scale and bias in the procedural
  testsuite/test_0013/data/shading.usda
  testsuite/test_0170/data/test.usda
  testsuite/test_0175/README
  testsuite/test_0175/data/test.usda
  testsuite/test_0175/data/texture.tx
  testsuite/test_0175/ref/reference.log
  testsuite/test_0175/ref/reference.tif
  translator/reader/read_shader.cpp
Labels: bug, procedural
