Repository Autodesk/arnold-usd, pull requests merged in 2022-10, with the labels that each got.

#1295 Support shader connections to mesh lights
  render_delegate/light.cpp
  render_delegate/light.h
  render_delegate/mesh.cpp
  testsuite/test_1294/README
  testsuite/test_1294/data/scene.usda
  testsuite/test_1294/ref/reference.log
  testsuite/test_1294/ref/reference.tif
  translator/reader/read_geometry.cpp
  translator/reader/read_light.cpp
  translator/reader/utils.cpp
  translator/reader/utils.h
Labels: enhancement, render delegate, procedural

#1312 Support AOV names called "color" for the beauty
  testsuite/test_1311/README
  testsuite/test_1311/data/test.usda
  testsuite/test_1311/ref/reference.log
  testsuite/test_1311/ref/reference.tif
  translator/reader/read_options.cpp
Labels: bug, procedural, user

#1314 Default render var's filter type to box instead of closest
  testsuite/test_1313/README
  testsuite/test_1313/data/test.usda
  testsuite/test_1313/ref/reference.log
  testsuite/test_1313/ref/reference.tif
  translator/reader/read_options.cpp
Labels: enhancement, procedural, user

#1310 Fix default width in rendervar's filters
  testsuite/test_0235/ref/reference.log
  testsuite/test_0235/ref/reference.tif
  testsuite/test_0236/ref/reference.log
  testsuite/test_0236/ref/reference.tif
  testsuite/test_0240/ref/reference.log
  testsuite/test_0240/ref/reference.tif
  testsuite/test_1309/README
  testsuite/test_1309/data/scene.usda
  testsuite/test_1309/ref/reference.log
  testsuite/test_1309/ref/reference.tif
  translator/reader/read_options.cpp
Labels: bug, procedural, user

#1308 Set driver's half_precision attribute
  testsuite/test_1232/README
  testsuite/test_1232/data/scene.usda
  testsuite/test_1232/ref/reference.exr
  testsuite/test_1232/ref/reference.log
  translator/reader/read_options.cpp
Labels: enhancement, procedural, user

#1325 add ENABLE_HYDRA_TEST variable and fix missing script issue
  SConstruct
  tools/utils/regression_test.py
Labels: test

#1328 Ensure that the ADP dialog box will not pop up and hang the application
  render_delegate/render_delegate.cpp
Labels: render delegate
