Repository Autodesk/arnold-usd, pull requests merged in 2022-04, with the labels that each got.

#1106 Compute visibility until the eventual root prim
  testsuite/test_0218/README
  testsuite/test_0218/data/test.usda
  testsuite/test_0218/ref/reference.log
  testsuite/test_0218/ref/reference.tif
  translator/reader/read_geometry.cpp
  translator/reader/reader.cpp
  translator/reader/reader.h
  translator/reader/utils.cpp
  translator/reader/utils.h
Labels: bug, procedural

#1108 Add aov_shaders after primvar AOVs.
  render_delegate/render_pass.cpp
  translator/reader/read_options.cpp
Labels: bug, render delegate, procedural

#1114 Remove deprecated API usage and compiler warnings in the procedural
  procedural/main.cpp
  translator/reader/prim_reader.cpp
  translator/reader/read_geometry.cpp
  translator/reader/read_light.cpp
  translator/reader/read_options.cpp
  translator/reader/read_shader.cpp
  translator/reader/reader.cpp
  translator/reader/reader.h
  translator/reader/registry.h
  translator/reader/utils.cpp
  translator/reader/utils.h
  translator/utils/utils.h
Labels: procedural

#1113 Build fix for procedural
  translator/reader/read_shader.cpp
  translator/reader/utils.cpp
  translator/reader/utils.h
  translator/writer/write_light.cpp
Labels: bug, procedural

#1111 Set color manager in reader (#1042)
  common/constant_strings.h
  render_delegate/render_delegate.cpp
  translator/reader/read_options.cpp
Labels: procedural

#1080 Geometry lights support in the render delegate
  common/constant_strings.h
  render_delegate/light.cpp
  render_delegate/light.h
  render_delegate/render_delegate.cpp
  render_delegate/utils.cpp
  schemas/createSchemaFile.py
  testsuite/test_0209/README
  testsuite/test_0209/data/test.usda
  testsuite/test_0209/ref/reference.log
  testsuite/test_0209/ref/reference.tif
  usd_imaging/CMakeLists.txt
  usd_imaging/SConscript
  usd_imaging/arnold_mesh_light_adapter.cpp
  usd_imaging/arnold_mesh_light_adapter.h
  usd_imaging/plugInfo.json.in
Labels: enhancement, render delegate

#1117 Support arnold primvars in instances
  common/constant_strings.h
  render_delegate/instancer.cpp
  render_delegate/utils.cpp
  render_delegate/utils.h
  testsuite/test_0219/README
  testsuite/test_0219/data/test.usda
  testsuite/test_0219/ref/reference.log
  testsuite/test_0219/ref/reference.tif
  translator/reader/prim_reader.cpp
  translator/reader/prim_reader.h
  translator/reader/read_arnold_type.cpp
  translator/reader/read_camera.cpp
  translator/reader/read_geometry.cpp
  translator/reader/read_light.cpp
  translator/reader/read_options.cpp
  translator/reader/read_shader.cpp
  translator/reader/reader.cpp
Labels: bug, render delegate, procedural, user

#1123 Fix build issue in procedural against USD 21.11
  translator/reader/utils.cpp
Labels: procedural, build

#1130 Support UsdPreviewSurface displacement output
  testsuite/test_0224/README
  testsuite/test_0224/data/scene.usda
  testsuite/test_0224/data/test.ass
  testsuite/test_0224/ref/reference.log
  testsuite/test_0224/ref/reference.tif
  translator/reader/utils.cpp
Labels: bug, procedural

#1129 Support UsdUvTexture relative paths with udims
  testsuite/test_0225/README
  testsuite/test_0225/data/asset/asset.usda
  testsuite/test_0225/data/test.usda
  testsuite/test_0225/data/tex/texture.1001.tx
  testsuite/test_0225/ref/reference.log
  testsuite/test_0225/ref/reference.tif
  translator/reader/prim_reader.cpp
  translator/reader/read_geometry.cpp
  translator/reader/read_light.cpp
  translator/reader/read_options.cpp
  translator/reader/utils.cpp
  translator/reader/utils.h
Labels: enhancement, procedural

#1128 Support light linking on instances
  render_delegate/shape.cpp
  testsuite/test_0223/README
  testsuite/test_0223/data/test.usda
  testsuite/test_0223/ref/reference.log
  testsuite/test_0223/ref/reference.tif
Labels: bug, render delegate, user

#1125 Optimize nested instances in the render delegate
  render_delegate/instancer.cpp
  render_delegate/instancer.h
  render_delegate/shape.cpp
  render_delegate/shape.h
  render_delegate/utils.cpp
  render_delegate/utils.h
Labels: enhancement, render delegate

#1121 Render NubsCurves as UsdGeomCurves
  testsuite/test_0220/README
  testsuite/test_0220/data/scene.usda
  testsuite/test_0220/data/test.ass
  testsuite/test_0220/ref/reference.log
  testsuite/test_0220/ref/reference.tif
  translator/reader/registry.cpp
Labels: enhancement, procedural

#1127 Support instanceable prims with variant & transform overrides
  testsuite/test_0218/ref/reference.log
  testsuite/test_0218/ref/reference.tif
  testsuite/test_0221/README
  testsuite/test_0221/data/test.usda
  testsuite/test_0221/ref/reference.log
  testsuite/test_0221/ref/reference.tif
  testsuite/test_0222/README
  testsuite/test_0222/data/test.usda
  testsuite/test_0222/data/test_asset_A.usda
  testsuite/test_0222/data/test_asset_B.usda
  testsuite/test_0222/ref/reference.log
  testsuite/test_0222/ref/reference.tif
  translator/reader/reader.cpp
  translator/reader/reader.h
  translator/reader/utils.cpp
  translator/reader/utils.h
Labels: enhancement, procedural

#1134 Set outputs layer names only if required #1133
  translator/reader/read_options.cpp
Labels: bug, procedural

#1137 Fix uninitialized UV coords with leftHanded meshes
  render_delegate/mesh.cpp
  render_delegate/utils.cpp
Labels: bug, render delegate
