Repository Autodesk/arnold-usd, pull requests merged in 2022-03, with the labels that each got.

#1053 Default mesh smoothing to true in the delegate
  render_delegate/mesh.cpp
Labels: enhancement, render delegate

#1050 Fix instanceable primitives without prototype
  testsuite/test_0157/data/scene.usda
  testsuite/test_0207/README
  testsuite/test_0207/data/cube.usda
  testsuite/test_0207/data/scene.usda
  testsuite/test_0207/data/test.ass
  testsuite/test_0207/ref/reference.log
  testsuite/test_0207/ref/reference.tif
  translator/reader/reader.cpp
Labels: bug, procedural, user

#1039 Use velocity/acceleration primvars for mesh/curves in the render delegate
  render_delegate/basis_curves.cpp
  render_delegate/mesh.cpp
  render_delegate/utils.cpp
Labels: bug, render delegate

#1055 Control scene_format_load thread count through an env variable
  procedural/SConscript
  procedural/main.cpp
  translator/CMakeLists.txt
Labels: enhancement, scene format

#1058 IPR improvements the arnold node graph adapter (#1057)
  common/constant_strings.h
  usd_imaging/node_graph_adapter.cpp
  usd_imaging/node_graph_adapter.h
Labels: render delegate

#1065 Sync AOV shaders referenced from the Render Settings in the delegate
  render_delegate/node_graph.cpp
  render_delegate/node_graph.h
  render_delegate/render_delegate.cpp
  render_delegate/render_delegate.h
  render_delegate/render_pass.cpp
  render_delegate/render_pass.h
Labels: render delegate

#1064 Set the defaultPrim in the usd writer
  common/constant_strings.h
  procedural/main.cpp
  translator/writer/writer.cpp
  translator/writer/writer.h
Labels: bug, scene format

#1066 Use custom metadata to store authored frames
  translator/writer/write_arnold_type.cpp
  translator/writer/writer.cpp
Labels: bug, writer

#1068 Write shading trees under their material's scope
  testsuite/test_0138/data/test.cpp
  testsuite/test_0208/README
  testsuite/test_0208/data/scene.ass
  testsuite/test_0208/data/test.cpp
  translator/writer/prim_writer.cpp
  translator/writer/writer.cpp
  translator/writer/writer.h
Labels: writer

#1076 Fix build issues with usd 21.02
  render_delegate/light.cpp
Labels: bug, build

#1082 Add point_light to the list of schemas to be generated #1081
  schemas/createSchemaFile.py
Labels: bug, schema

#1088 Fix attribute calls in camera reader that were causing random crashes
  translator/reader/read_camera.cpp
Labels: bug, procedural, scene format, user

#1094 Fix instanceable references in the same usd file
  testsuite/test_0215/README
  testsuite/test_0215/data/test.usda
  testsuite/test_0215/ref/reference.log
  testsuite/test_0215/ref/reference.tif
  translator/reader/reader.cpp
Labels: bug, procedural, user
