Repository Autodesk/arnold-usd, pull requests merged in 2022-01, with the labels that each got.

#995 Fix arnold node graph adapter for USD 21.08
  usd_imaging/node_graph_adapter.cpp
Labels: bug, render delegate

#993 Support nested instancer primvars in the render delegate
  render_delegate/instancer.cpp
  render_delegate/instancer.h
  render_delegate/shape.cpp
  render_delegate/utils.cpp
  render_delegate/utils.h
  testsuite/test_0194/README
  testsuite/test_0194/data/test.usda
  testsuite/test_0194/data/test_parent.usda
  testsuite/test_0194/ref/reference.log
  testsuite/test_0194/ref/reference.tif
Labels: enhancement, render delegate

#997 Support point instancer with a cache_id in the procedural
  common/constant_strings.h
  translator/reader/read_geometry.cpp
  translator/reader/reader.h
Labels: bug, procedural

#999 Ensure the preview surface opacity is set correctly
  testsuite/test_0195/README
  testsuite/test_0195/data/USDLogoLrg.png
  testsuite/test_0195/data/scene.usda
  testsuite/test_0195/data/test.ass
  testsuite/test_0195/ref/reference.log
  testsuite/test_0195/ref/reference.tif
  translator/reader/read_shader.cpp
Labels: bug, procedural

#1011 Fix shadow/light linking when some lights don't have any collection
  testsuite/test_0200/data/test.usda
  testsuite/test_0200/ref/reference.log
  testsuite/test_0200/ref/reference.tif
  translator/reader/reader.cpp
Labels: bug, procedural

#1015 Remove harmless warnings when declaring a user data #1014
  translator/reader/prim_reader.cpp
Labels: bug, procedural
